name: nearbii
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0+5

environment:
  sdk: "2.19.6"

dependencies:
  animate_icons: ^2.0.0
  avatar_glow: ^2.0.2
  bottom_navy_bar: ^6.0.0
  cached_network_image: ^3.2.2
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.1.14
  csc_picker: ^0.2.6
  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.2
  easy_image_viewer: ^1.1.0
  easy_pdf_viewer: ^1.0.3
  firebase_auth: ^3.3.17
  firebase_core: ^1.16.0
  firebase_messaging: ^13.1.0
  firebase_storage: any
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_facebook_auth: ^5.0.8
  flutter_html: ^3.0.0-alpha.2
  flutter_launcher_icons: ^0.12.0
  flutter_local_notifications: ^13.0.0
  flutter_rating_bar: ^4.0.0
  flutter_share: ^2.0.0
  flutter_staggered_grid_view: ^0.6.1
  fluttertoast: ^8.0.9
  geocoding: ^2.0.4
  geoflutterfire: ^3.0.3
  geolocator: ^9.0.2
  google_maps_flutter: ^2.1.4
  google_mobile_ads: ^3.0.0
  google_sign_in: ^6.0.2
  highlight_text: ^1.3.0
  image: ^4.0.15
  image_picker: ^0.8.5
  intl: ^0.17.0
  maps_launcher: ^2.0.1
  month_year_picker: ^0.2.0+1
  notification_permissions: ^0.6.1
  path: ^1.8.0
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  pinput: ^2.2.31
  qr_code_scanner: ^1.0.0
  qr_flutter: ^4.0.0
  razorpay_flutter: ^1.3.0
  readmore: ^2.2.0
  rename: ^2.0.1
  shared_preferences: ^2.0.15
  shared_storage: ^0.7.0
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  speech_to_text: ^6.1.1
  swipe_refresh: ^1.0.2
  velocity_x: ^3.5.1
  wc_flutter_share: ^0.4.0

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  dart_code_metrics: ^5.6.0
  dependency_validator: ^3.0.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/iconNew.png"
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/home_services/
    - assets/images/item_images/
    - assets/images/services/
    - assets/images/travel/
    - assets/images/more/
    - assets/images/clothes_and_apparel/
    - assets/images/daily_need/
    - assets/images/repairs_and_services/
    - assets/images/street-food/
    - assets/images/education/
    - assets/images/trainingInstitute/
    - assets/images/loading_screen/
    - assets/images/authentication/
    - assets/images/splash_screen/
    - assets/images/drawer/
    - assets/images/events/
    - assets/images/no_internet/
    - assets/images/advertise/
    - assets/images/categories/
    - assets/images/categories/restaurants/
    - assets/images/advertise/plans/
    - assets/images/offers/
    - assets/images/scan/
    - assets/images/membership_plan/
    - assets/images/profile/
    - assets/images/profile/user_profile/
    - assets/images/profile/vendor_profile/
    - assets/images/profile/vendor_profile/photos/
    - assets/icons/
    - assets/icons/wallet/
    - assets/icons/privacy_settings/
    - assets/icons/drawer_icons/
    - assets/icons/plans/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
